#!/bin/sh



if [ -e /usr/local/bin/ffUUID ]; then
  . /usr/local/bin/ffUUID
  DRVNM=`blkid | grep -e $UUIDFF | cut -d "/" -f 3- | cut -d ":" -f -1`
  echo $DRVNM
  mount /dev/${DRVNM} /mnt/${DRVNM} > /dev/null 2>&1
  if [ -e /mnt/$DRVNM/$FFDIR/firefox ]; then
     cd /mnt/$DRVNM/$FFDIR
     /mnt/$DRVNM/$FFDIR/ff "$@"
  else
    echo "$FFDIR cannot be found. Do you wish to reinstall? y/n"
    read YN
    if [[ $YN == "y" ]];then
      /usr/local/bin/ffportable-inst
    else
      exit
    fi
  fi
else 
  /usr/local/bin/ffportable-inst
fi

