#!/bin/bash

#jrb - start
#open in terminal
tty -s; if [ $? -ne 0 ]; then defaultterminal -hold -e "$0"; exit; fi
set -x
message_fn(){
  args=()
  gx_options=()
  while [ $# -gt 0 ]; do
    if [ $1 = "-file" ]; then
      args=( "$1" )
      shift
      args+=( "$1" )
      message_file
      shift
    elif [ $1 = "-bg" ]; then
      gx_options=( "$1" )
      shift
      gx_options=( "$1" )
      shift      
    else
      args+="$1"
      shift
    fi
  done
  if [ ! -z "`which gxmessage`" ]; then
    gxmessage "${gx_options}" "${args[@]}"
  elif [ ! -z "`which xmessage`" ]; then
    xmessage "${options[@]}" "$@"
  else
    [ -z "$message" ] && 
    cat /usr/share/doc/ffportable
    read -p "Press enter to continue"
  fi
}
[ -e /usr/share/doc/ffportable ] && \
  message_fn -bg yellow -file /usr/share/doc/ffportable

. /usr/local/bin/ffUUID > /dev/null 2>&1

if [ -e /usr/local/bin/ffUUID ]; then
  [ ! -z "$UUIDFF" ] && \
    DRVNM=`blkid | grep -e $UUIDFF | cut -d "/" -f 3- | cut -d ":" -f -1`
  [ ! -z "$DRVNM" ] && mount /dev/${DRVNM} /mnt/${DRVNM} > /dev/null 2>&1
  echo "FirefoxPortable has already been installed.  Do you wish to reinstall? y/n"  
  read YN
  if [ $YN == "y" ]; then
    rm -f /usr/local/bin/ffUUID
  else
    exit
  fi
fi

#choose drive
echo "What drive would you like to install FirefoxPortable on? eg: sda3"
read DRVNM

#mount drive
if [ ! "${DRVNM:0:1}" = "/" ]; then
  mkdir -p /mnt/$DRVNM > /dev/null 2>&1
  [ -e /dev/$DRVNM ] && mount /dev/$DRVNM /mnt/$DRVNM > /dev/null 2>&1

  #switch to drive
  cd "/mnt/$DRVNM"
else
  mkdir -p "$DRVNM" > /dev/null 2>&1
  cd "$DRVNM"
fi

#switch to drive
cd /mnt/$DRVNM

#identify firefox drive placement by uuid in case of flashdrive installs
rm /usr/local/bin/ffUUID > /dev/null 2>&1
echo /bin/bash > /usr/local/bin/ffUUID
sed -i 's|/bin/bash|#!/bin/bash|g' /usr/local/bin/ffUUID
chmod +x /usr/local/bin/ffUUID

UUIDFF2=`blkid /dev/$DRVNM | cut -d " " -f 2`
echo $UUIDFF2 >> /usr/local/bin/ffUUID
sed -i 's/"//g' /usr/local/bin/ffUUID
sed -i 's/UUID/UUIDFF/g' /usr/local/bin/ffUUID
echo "DRVNM_ALT='$DRVNM'" >> /usr/local/bin/ffUUID

#jrb - stop

#fredx181 - start
# set language, see here which are available: https://ftp.mozilla.org/pub/firefox/releases/latest/README.txt
FFLANG=en-US

if [ "$(uname -m)" = "i686" ]; then
FFARCH=linux
elif [ "$(uname -m)" = "x86_64" ]; then
message_fn -bg red "This program is only for 32bit systems"
exit
fi

# check version
VERSION=$(wget -c --no-check-certificate --spider -S --max-redirect 0 "https://download.mozilla.org/?product=firefox-latest&os=${FFARCH}&lang=${FFLANG}" 2>&1 | sed -n '/Location: /{s|.*/firefox-\(.*\)\.tar.*|\1|p;q;}')

# download firefox
echo "Downloading Firefox..."
echo
wget -c --no-check-certificate "https://download.mozilla.org/?product=firefox-latest&os=${FFARCH}&lang=${FFLANG}" -O "FF_${VERSION}_32.tar.bz2"
echo

echo "Extracting Firefox..."
if [ -d firefox_${VERSION}_32 ]; then
  echo "y/n remove directory $(realpath "firefox_${VERSION}_32")"
  read YN
  if [[ $YN == "y" ]]; then #TODO add option to keep previous user settings
    rm -rf firefox_${VERSION}_32
    mkdir firefox_${VERSION}_32
  else
    exit
  fi
else
  mkdir firefox_${VERSION}_32
fi
tar -xjf "FF_${VERSION}_32.tar.bz2" -C firefox_${VERSION}_32 --strip-components=1
wget -c --no-check-certificate "https://dl.dropboxusercontent.com/s/3rn1a4e4scmfdyv/ff32-additions.tar.gz?dl=1" -O ff32-additions.tar.gz
tar -zxf ff32-additions.tar.gz -C firefox_${VERSION}_32
echo "Done, the portable firefox folder is firefox_${VERSION}_32"
echo "You can now delete the archives:"
echo "FF_${VERSION}_32.tar.bz2 and ff32-additions.tar.gz"

#identify Firefox directory
  echo "FFDIR=firefox_${VERSION}_32" >> /usr/local/bin/ffUUID

ln -s /usr/local/PortableBrowserInstaller/ffportable_launch /usr/local/bin
ln -s /usr/local/PortableBrowserInstaller/Firefox-portable.desktop /usr/share/applications
fixmenus
jwm -reload

#start firefox-portable
. /usr/local/bin/ffUUID

DRVNM=`blkid | grep -e $UUIDFF | cut -d "/" -f 3- | cut -d ":" -f -1`
echo $DRVNM
DRVNM="${DRVNM:-$DRVNM_ALT}"

if [ -d "/mnt/$DRVNM/$FFDIR" ]; then
  #/mnt/$DRVNM/$FFDIR/firefox
  cp /usr/local/PortableBrowserInstaller/ff "/mnt/$DRVNM/$FFDIR"
  cd "/mnt/$DRVNM/$FFDIR"
  "/mnt/$DRVNM/$FFDIR/ff" "$@"
else
  #/mnt/$DRVNM/$FFDIR/firefox
  cp /usr/local/PortableBrowserInstaller/ff "$DRVNM/$FFDIR"
  cd "$DRVNM/$FFDIR"
  "$DRVNM/$FFDIR/ff" "$@"
fi

echo
echo
echo "Would you like to make Firefox the default browser? y/n"
read YN
if [[ $YN == "y" ]]; then
  cp -f /usr/local/PortableBrowserInstaller/defaultbrowser /usr/local/bin
  echo ffportable_launch "$@" >> /usr/local/bin/defaultbrowser
else
  exit
fi
 

