#!/bin/sh

LAUNCHDIR="$(cd "$(dirname "$0")"; pwd)"
#LAUNCHDIR="$(dirname "$(readlink -f "$0")")"
mkdir "$LAUNCHDIR/profile" 2> /dev/null
#LD_LIBRARY_PATH=$LAUNCHDIR/apulse${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH} "$LAUNCHDIR/palemoon" "$@" -profile "$LAUNCHDIR/profile"

"$LAUNCHDIR/palemoon" "$@" -profile "$LAUNCHDIR/profile"
