#!/bin/sh



if [ -e /usr/local/bin/pmUUID ]; then
  . /usr/local/bin/pmUUID
  DRVNM=`blkid | grep -e $UUIDPM | cut -d "/" -f 3- | cut -d ":" -f -1`
  echo $DRVNM
  mount /dev/${DRVNM} /mnt/${DRVNM} > /dev/null 2>&1
  if [ -e /mnt/$DRVNM/$PMDIR/palemoon ]; then
    /mnt/$DRVNM/$PMDIR
    /mnt/$DRVNM/$PMDIR/pm "$@"
  else
    echo "$PMDIR cannot be found. Do you wish to reinstall? y/n"
    read YN
    if [[ $YN == "y" ]];then
      /usr/local/bin/pmportable-inst
    else
      exit
    fi
  fi
else 
  /usr/local/bin/pmportable-inst
fi

