#!/bin/sh
#
#Selector for portable web browsers, copied from © Mike Walsh Apr 2018
#

#/usr/local/PortableBrowserInstaller/yad_dnld.sh

if [ ! -z "`which yad`" ]; then

yad --center --window-icon=/usr/local/lib/X11/pixmaps/www48.png --title="Portable Web Browser Installer" --form --width=450 --text="PORTABLE WEB BROWSER INSTALLER
--------------------------------------------------
Please choose your desired browser:" \
--image="/usr/local/lib/X11/pixmaps/www48.png" \
--field="Firefox Quantum":fbtn "ffinst" \
--field="Palemoon":fbtn "pminst" \
--field="Seamonkey":fbtn "sminst" \
--field="Thunderbird email client":fbtn "tbinst" \
--no-buttons --close-on-unfocus

else
  tty -s; if [ $? -ne 0 ]; then defaultterminal -hold -e "$0"; exit; fi
  dialog --backtitle "CPU Selection" \
  --radiolist "Please choose your desired browser:" 10 40 4 \
        1 Firefox Quantum \
        2 Palemoon \
        3 Seamonkey \
        4 Thunderbird email client
  browser_choice="$?"
  case "$browser_choice" in
  1) ffinst ;;
  2) pminst ;;
  3) sminst ;;
  4) tbinst ;;
fi 