#!/bin/sh



if [ -e /usr/local/bin/smUUID ]; then
  . /usr/local/bin/smUUID
  DRVNM=`blkid | grep -e $UUIDSM | cut -d "/" -f 3- | cut -d ":" -f -1`
  echo $DRVNM
  mount /dev/${DRVNM} /mnt/${DRVNM} > /dev/null 2>&1
  if [ -e /mnt/$DRVNM/$SMDIR/seamonkey ]; then
    cd /mnt/$DRVNM/$SMDIR
    /mnt/$DRVNM/$SMDIR/sm "$@"
  else
    echo "$SMDIR cannot be found. Do you wish to reinstall? y/n"
    read YN
    if [[ $YN == "y" ]];then
      /usr/local/bin/smportable-inst
    else
      exit
    fi
  fi
else 
  /usr/local/bin/smportable-inst
fi

