#!/bin/bash

#jrb - start
#open in terminal

tty -s; if [ $? -ne 0 ]; then defaultterminal -hold -e "$0"; exit; fi

message_fn(){
  args=()
  gx_options=()
  while [ $# -gt 0 ]; do
    if [ $1 = "-file" ]; then
      args=( "$1" )
      shift
      args+=( "$1" )
      message_file
      shift
    elif [ $1 = "-bg" ]; then
      gx_options=( "$1" )
      shift
      gx_options=( "$1" )
      shift      
    else
      args+="$1"
      shift
    fi
  done
  if [ ! -z "`which gxmessage`" ]; then
    gxmessage "${gx_options}" "${args[@]}"
  elif [ ! -z "`which xmessage`" ]; then
    xmessage "${options[@]}" "$@"
  else
    [ -z "$message" ] && 
    cat /usr/share/doc/ffportable
    read -p "Press enter to continue"
  fi
}
[ -e /usr/share/doc/tbportable ] && \
  message_fn -bg yellow -file /usr/share/doc/tbportable

. /usr/local/bin/tbUUID > /dev/null 2>&1

if [ -e /usr/local/bin/tbUUID ]; then
  [ ! -z "$UUIDFF" ] && \
    DRVNM=`blkid | grep -e $UUIDtb | cut -d "/" -f 3- | cut -d ":" -f -1`
  [ ! -z "$DRVNM" ] && mount /dev/${DRVNM} /mnt/${DRVNM} > /dev/null 2>&1
  echo "ThunderbirdPortable has already been installed.  Do you wish to reinstall? y/n"  
  read YN
  if [ $YN == "y" ]; then
    rm -f /usr/local/bin/tbUUID
  else
    exit
  fi
fi

#choose drive
echo "What drive would you like to install ThunderbirdPortable on? eg: sda3"
read DRVNM

#mount drive
if [ ! "${DRVNM:0:1}" = "/" ]; then
  mkdir -p /mnt/$DRVNM > /dev/null 2>&1
  [ -e /dev/$DRVNM ] && mount /dev/$DRVNM /mnt/$DRVNM > /dev/null 2>&1

  #switch to drive
  cd "/mnt/$DRVNM"
else
  mkdir -p "$DRVNM" > /dev/null 2>&1
  cd "$DRVNM"
fi

#switch to drive
cd /mnt/$DRVNM

#identify Thunderbird drive placement by uuid in case of flashdrive installs
rm /usr/local/bin/tbUUID > /dev/null 2>&1
echo /bin/bash > /usr/local/bin/tbUUID
sed -i 's|/bin/bash|#!/bin/bash|g' /usr/local/bin/tbUUID
chmod +x /usr/local/bin/tbUUID

UUIDtb2=`blkid /dev/$DRVNM | cut -d " " -f 2`
echo $UUIDtb2 >> /usr/local/bin/tbUUID
sed -i 's/"//g' /usr/local/bin/tbUUID
sed -i 's/UUID/UUIDTB/g' /usr/local/bin/tbUUID
echo "DRVNM_ALT='$DRVNM'" >> /usr/local/bin/tbUUID

# check arch
if [ "$(uname -m)" = "i686" ]; then
TBARCH=linux
elif [ "$(uname -m)" = "x86_64" ]; then
message_fn -bg red "This program is only for 32bit systems"
exit
fi

# check version
  TBRD=`curl -ks https://www.thunderbird.net/en-US/download/ | grep "product=thunderbird" | cut -d '"' -f 2-4 | grep "linux&" | cut -d '"' -f 1`
  TBRDVER=`echo $TBRD | cut -d "-" -f 2`  #60.6.1
  mkdir Thunderbird_${TBRDVER}_32
  echo "Downloading Thunderbird..."
  wget -c --no-check-certificate -O thunderbird-"${TBRDVER}".tar.bz2 ${TBRD}

echo $TBRD

echo
echo "Extracting Thunderbird..."
tar -xjf thunderbird-"${TBRDVER}".tar.bz2 -C Thunderbird_${TBRDVER}_32 --strip-components=1
echo "Done, the portable Thunderbird folder is Thunderbird_${TBRDVER}_32"
echo "You can now delete the archive:"
echo "thunderbird_${TBRDVER}_32.tar.bz2"
echo

#identify Thunderbird directory
  echo "TBDIR=Thunderbird_${TBRDVER}_32" >> /usr/local/bin/tbUUID

ln -s /usr/local/PortableBrowserInstaller/tbportable_launch /usr/local/bin
ln -s /usr/local/PortableBrowserInstaller/Thunderbird-portable.desktop /usr/share/applications
fixmenus
jwm -reload

#start Thunderbird-portable
. /usr/local/bin/tbUUID

DRVNM=`blkid | grep -e $UUIDTB | cut -d "/" -f 3- | cut -d ":" -f -1`
echo $DRVNM
DRVNM="${DRVNM:-$DRVNM_ALT}"

if [ -d "/mnt/$DRVNM/$TBDIR" ]; then
  cp /usr/local/PortableBrowserInstaller/tb "/mnt/$DRVNM/$TBDIR"
  cd "/mnt/$DRVNM/$TBDIR"
  "/mnt/$DRVNM/$TBDIR/tb" "$@"
else
  cp /usr/local/PortableBrowserInstaller/tb "$DRVNM/$TBDIR"
  cd "$DRVNM/$TBDIR"
  "$DRVNM/$TBDIR/tb" "$@"
fi

echo
echo
echo "Would you like to make Thunderbird the default email client? y/n"
read YN
if [[ $YN == "y" ]]; then
  cp -f /usr/local/PortableBrowserInstaller/defaultemail /usr/local/bin
  echo tbportable_launch "$@" >> /usr/local/bin/defaultemail
else
  exit
fi
 

