#!/bin/sh



if [ -e /usr/local/bin/tbUUID ]; then
  . /usr/local/bin/tbUUID
  DRVNM=`blkid | grep -e $UUIDTB | cut -d "/" -f 3- | cut -d ":" -f -1`
  echo $DRVNM
  DRVNM="${DRVNM:-DRVNM_ALT}"
  [ -e /dev/${DRVNM} ] && mount /dev/${DRVNM} /mnt/${DRVNM} > /dev/null 2>&1
  if [ -e "/mnt/$DRVNM/$TBDIR/thunderbird" ]; then
    "/mnt/$DRVNM/$TBDIR"
    "/mnt/$DRVNM/$TBDIR/tb" "$@"
  elif [ -e "/mnt/$DRVNM/$TBDIR/thunderbird" ]; then
    "/mnt/$DRVNM/$TBDIR"
    "/mnt/$DRVNM/$TBDIR/tb" "$@"    
  else
    echo "$TBDIR cannot be found. Do you wish to reinstall? y/n"
    read YN
    if [[ $YN == "y" ]];then
      /usr/local/bin/tbportable-inst
    else
      exit
    fi
  fi
else 
  /usr/local/bin/tbportable-inst
fi

