#!/bin/sh

if [ -e /proc/acpi/battery/BAT0 ]; then
Xdialog --title "Battery Information" --fixed-font --tailbox /proc/acpi/battery/BAT0/info 20 50
else
/usr/lib/gtkdialog/box_ok "Notice" info "No battery present. The computer is currently plugged on AC"
fi
